language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
    - install -g npm@'>=2.13.0'
    - npm install -g grunt-cli
    - npm install -g bower
script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
